num_actors: 4

replay_buffer_size: 80000
replay_buffer_episode: 2000

model_pool_size: 10
model_pool_name: "model-pool"

gamma: 0.98
gae_lambda: 0.95
min_sample: 1000
batch_size: 64
epochs: 10
clip: 0.3
lr: 0.001
value_coeff: 0.5
entropy_coeff: 0.3
device: "cuda"
max_iterations: 100000

log_interval: 10
ckpt_save_interval: 10000
eval_interval: 1000
output_path: "./output"

use_curriculum: True
curriculum_data_folder: "./curriculum_data"
curriculum_iterations:
  - 10000
  - 20000
  - 30000
  - 40000
  - 50000
  - 60000

use_BC: True
use_curriculum_for_BC: True
BC_iterations: 200000
curriculum_iterations_for_BC:
  - 30000
  - 60000
  - 90000
  - 120000
  - 150000
  - 180000
