num_actors: 5

replay_buffer_size: 100000
replay_buffer_episode: 1000

model_pool_size: 20
model_pool_name: "model-pool"

gamma: 0.98
gae_lambda: 0.95
min_sample: 1000
batch_size: 256
epochs: 5
clip: 0.2
lr: 0.00001
value_coeff: 0.5
entropy_coeff: 0.1
device: "cuda"
max_iterations: 1000000

log_interval: 10
ckpt_save_interval: 100000
eval_interval: 1000
output_path: "./output"

use_curriculum: True
curriculum_data_folder: "./curriculum_data"
curriculum_iterations:
  - 100000
  - 200000
  - 300000
  - 400000
  - 500000
  - 600000
